#!/bin/bash

function printbar () {
  local value=$1
  local total=$2
  local i=0
  echo -en "\rProgress: $value/$total ["
  for (( ; i<10; i++ )); do
    if (( i >= (value*10)/total )); then
      echo -n "$(tput setab 1)"    #green
    else
      echo -n "$(tput setab 2)"    #red
    fi
    echo -n " "
  done
  echo -n "$(tput sgr 0)]"
}

