#!/usr/bin/env bash

mkdir -p /tmp/libash

# reset sane defaults
PS1='\u@\h \w \$ '
PS2='> '
PS3='> '
PS4='+ '
PROMPT_COMMAND=


# case insensitive matching and completion
# LIBASH_CASE=no

[[ -r /usr/share/bash-completion/bash_completion ]] && . /usr/share/bash-completion/bash_completion

shopt -s extglob globstar
for file in "$LIBASHDIR/scripts/"!(magicalias) ; do
  source "$file"
done

[[ $- = *i* ]] && source "$LIBASHDIR/scripts/magicalias"

[[ -r ~/.config/libash ]] && source ~/.config/libash
