#!/usr/bin/env bash

mkdir -p /tmp/libash

# reset sane defaults
PS1='\u@\h \w \$ '
PS2='> '
PS3='> '
PS4='+ '
PROMPT_COMMAND=


# case insensitive matching and completion
# LIBASH_CASE=no

[[ -r /usr/share/bash-completion/bash_completion ]] && . /usr/share/bash-completion/bash_completion

sourcelibash () {
  local file array
  shopt -s extglob globstar
  # keep. the. order.
  LC_COLLATE=C eval 'array=("$LIBASHDIR/scripts/"!(*alias|*notready*))'
  for file in "${array[@]}"; do
    source "$file"
  done

  if [[ $- = *i* ]]; then
    for file in "$LIBASHDIR"/scripts/*alias; do
      source "$file"
    done
  fi
}
sourcelibash

# much betta
TIMEFORMAT=$'\nreal: %lR, user: %lU, sys: %lS'


[[ -r ~/.config/libash ]] && source ~/.config/libash
