#!/bin/bash



# partial rewrite of compgen
# mainly to add a separator option
libash_compgen () {
  OPTIND=1
  local opt d=: f=: S='\n' completions comp case
  while getopts dfzS: opt; do
    case $opt in
      d) d=;;        # dirnames
      f) f=;;        # filenames
      z) S='\0';;    # NUL delimited
      S) S=$OPTARG;; # OPTARG delimited
    esac
  done
  shift $((OPTIND-1))
  [[ -d $1 && $1 != */ ]] && set -- "$1"/
  if shopt -q nocaseglob; then case=no; fi
  if [[ $LIBASH_CASE = no || $(bind -v) = *"completion-ignore-case on"* ]]; then
    shopt -s nocaseglob
  fi
  completions=("$1"*)
  if [[ $case = no ]]; then shopt -u nocaseglob; fi
  for comp in "${completions[@]}"; do
    if [[ -f $comp ]]; then
      $f printf "%s$S" "$comp"
    elif [[ -d $comp ]]; then
      $d printf "%s$S" "$comp"
    fi
  done
}

# avoid opening binary files / pictures with vim
_vim () {
  local type path
  case $2 in
    '~') path=$HOME;;
    '~/'*) path=${2/'~'/"$HOME"};;
    *) path=$2;;
  esac
  [[ -d $path ]] && path=${path%/}/
  # read filename
  while read -r -d ''; do
    # mime type (remove : and leading whitespace)
    read -r _ type;
    if [[ $type = text* ]]; then
      [[ $REPLY = "$HOME"/* && $2 = '~'* ]] && REPLY=${REPLY/"$HOME"/'~'}
      COMPREPLY+=("$REPLY")
    fi
  done < <(
            if [[ $LIBASH_CASE = no || $(bind -v) = *"completion-ignore-case on"* ]]; then
              shopt -s nocaseglob
            fi
            shopt -s nullglob
            # whitelist: (don't check these, add them by default)
            # c|h|hpp|cpp|txt|md|tex|py|sh
            # blacklist: (don't check these either)
            # png|jpg|jpeg|gif|mp4|mp3|ogg|tar|gz|xz|bz2|lzma|pdf|a|o|so|wav|flac|mov|flv|avi
            file --mime-type -0 -L -r -- /dev/null "$path"!(*.@(png|jp?(e)g|gif|mp[34]|ogg|tar|gz|xz|bz2|lzma|pdf|a|o|so|wav|flac|mov|flv|avi|c|h|hpp|cpp|txt|md|tex|py|sh))

            arr=( "$path"*@(.@(c|h|hpp|cpp|txt|md|tex|py|sh)) )
            (( ${#arr[@]} )) && printf '%s\0: text\n' "${arr[@]}"
            )

  # FIXME
  # when you're trying to complete ~ without / it doesn't show the directories

  # workaround, not perfect
  if [[ $2 = '~' ]]; then
    shopt -s nullglob
    local dirs=(~/*/)
    shopt -u nullglob
    dirs=("${dirs[@]%/}") dirs=("${dirs[@]/"$HOME"/'~'}")
    COMPREPLY+=("${dirs[@]}")
  fi
}

complete -o plusdirs -F _vim vim

# use this in case file fails detect a file as text
# or in huge directories with thousands of file
alias __vim=vim



_busybox () {
  if (( ${#COMP_WORDS[@]} < 3 )); then
    while read -r; do
      [[ $REPLY = "$2"* ]] && COMPREPLY+=("$REPLY")
    done < <(busybox --list)
  else
    compopt -o bashdefault
    compopt -o default
    compopt -o filenames
  fi
}
complete -F _busybox busybox

_toybox () {
  if (( ${#COMP_WORDS[@]} < 3 )); then
    while read -r; do
      [[ $REPLY = "$2"* ]] && COMPREPLY+=("$REPLY")
    done < <(toybox | tr ' ' '\n')
  else
    compopt -o bashdefault
    compopt -o default
    compopt -o filenames
  fi
}
complete -F _toybox toybox
