#!/usr/bin/env bash

# chpwd_hook will return true when you just changed directory

chpwd_hook () {
  local chpwd=1
  [[ $olddir ]] && [[ $olddir != "$PWD" ]] && chpwd=0
  olddir=$PWD
  return $chpwd
}

