#!/usr/bin/env bash

# chpwd_hook will return true when you just changed directory

chpwd_hook () {
  local chpwd=1
  [[ $olddir ]] && [[ $olddir != "$PWD" ]] && chpwd=0
  olddir=$PWD
  return $chpwd
}

periodic_hook () {
  [[ $1 ]] && : todo
}

add_to_hook () {
  : to do
}
