#!/usr/bin/env bash

: << :
progress bars
-------------

usage:

colorbar "0" "$max"
for (( i=0; i<max; i++ )) ; do
  wget -q "$url/$i.png"
  colorbar $((i+1)) "$max"
done

the second one was my attempt at a progress bar in as few characters as possible
works like the first one
:

colorbar () {
  local value="$1"
  local total="$2"
  local i=0
  printf "["
  for (( ; i<10; i++ )); do
    if (( i >= (value*10)/total )); then
      tput setab 1    #red
    else
      tput setab 2    #green
    fi
    printf " "
  done
  tput sgr0
  printf "] Progress: %d/%d" "$value" "$total"
  [[ -n $3 ]] && printf -- " - %s" "$3"
  [[ $1 != $2 ]] && printf "\r" || echo
}

bwbar()(b=[;for i in {1..9};do((i>$1*9/$2))&&b+=-||b+=#;done;(($1==$2))&&echo $b]||printf "$b]\r";)

