#!/usr/bin/env bash

# replicas of moreutils

sponge () {
  local file=$(mktemp) && \
  cat > "$file" && \
  cat "$file" > "$1" && \
  rm "$file"
}

ts () {
  local format=+%c
  [[ $1 ]] && format=+$1
  while read -r ; do
    timestamp=$(date "$format")
    printf '%s %s\n' "$timestamp" "$REPLY"
  done
}
